version: '2'

volumes:
  postgres-data:
    external: false

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./app/backend
    container_name: backend
    volumes:
      - ./app/backend:/opt/app
    command: foreman start -f Procfile.dev
    env_file:
      - 'app/backend/config/application.yml'
    ports:
      - '3000:3000'
      - '3035:3035'
    depends_on:
      - db
  
  frontend:
    build: ./app/frontend
    container_name: frontend
    volumes:
      - ./app/frontend:/opt/app

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    container_name: nginx
    volumes:
      - ./nginx/configs:/etc/nginx/conf.d/
      - ./app/frontend/:/usr/share/nginx/html/
    ports:
      - 80:80

  redis:
    image: redis:3.2-alpine
    depends_on:
      - backend
    container_name: redis
